<?php


namespace App;


class ConstValue
{

    /*********************************** 
     * Project Context Contsant Value  *
     ***********************************/

    /**
     * Project Id
     */
    const PROJECT_ID_MICROFINANCE = 1;
    const PROJECT_ID_GENERAL = 5;
    const PROJECT_ID_RADIO_BIKRAMPUR = 7;

    /**
     * Position Id
     */
    const POSITION_ID_ADDITIONAL_DIRECTOR = 107;
    const POSITION_ID_AREA_MANAGER = 131;
    const POSITION_ID_ASSISTANT_DIRECTOR = 109;
    const POSITION_ID_BRANCH_MANAGER = 125;
    const POSITION_ID_DEPUTY_EXECUTIVE_DIRECTOR = 105;
    const POSITION_ID_DEPUTY_DIRECTOR = 108;
    const POSITION_ID_DIRECTOR = 106;
    const POSITION_ID_EXECUTIVE_DIRECTOR = 104;
    const POSITION_ID_PROGRAM_MANAGER = 129;
    const POSITION_ID_ZONAL_MANAGER = 130;

    /**
     * Recruitment Type Id
     */
    const RECRUITMENT_TYPE_REGULAR_ID = 1;

    /************************************** 
     * Application Context Constant Value  *
     ***************************************/

    /**
     * Reporting Boss Rule Key
     */
    const REPORTING_BOSS_RULE_KEY_SUPER_BOSS = 'super_boss';
    const REPORTING_BOSS_RULE_KEY_AREA_BOSS = 'area_boss';
    const REPORTING_BOSS_RULE_KEY_ZONAL_BOSS = 'zonal_boss';
    const REPORTING_BOSS_RULE_KEY_BRANCH_BOSS = 'branch_boss';
    const REPORTING_BOSS_RULE_KEY_PROGRAM_BOSS = 'program_boss';

    /**
     * GNR Responsibility Type Code
     */
    const RESPONSIBILITY_TYPE_CODE_AREA = 'AREA';
    const RESPONSIBILITY_TYPE_CODE_ZONE = 'ZONE';
    const RESPONSIBILITY_TYPE_CODE_REGION = 'REGION';

    /**
     * Branch Id
     */
    const BRANCH_ID_HEAD_OFFICE = 1;
    const BRANCH_ID_SUPER_ADMIN = 1;

    /**
     * User Id
     */
    const USER_ID_SUPER_ADMIN = 1;

    /**
     * Role Id
     */
    const ROLE_ID_SUPER_ADMIN = 1;
    const ROLE_ID_EMPLOYEE = 2;
    const ROLE_ID_GUEST = 3;

    /**
     * Status Code
     */
    const STATUS_CODE_NOT_FOUND = 404;
    const STATUS_CODE_SUCCESS = 200;
    const STATUS_CODE_SERVER_ERROR = 500;

    /**
     * Module Id
     */
    const MODULE_ID_HR = 5;

    /**
     * Sub Function Id
     */
    const SUB_FUNCTION_ID_VIEW = 1;
    const SUB_FUNCTION_ID_CREATE = 2;
    const SUB_FUNCTION_ID_EDIT = 3;
    const SUB_FUNCTION_ID_DELETE = 4;
    const SUB_FUNCTION_ID_LIST = 5;
    const SUB_FUNCTION_ID_APPROVE = 7;
    const SUB_FUNCTION_ID_ALL_DATA = 8;


    /**
     * Function Code
     */

    // Information
    const FUNCTION_CODE_EMPLOYEE_LIST = '05007';

    // Leave Application
    const FUNCTION_CODE_LEAVE_APPLICATION = '05021';

    // Attendance
    const FUNCTION_CODE_ATTENDANCE_LIST = '05027';

    // Recruitment
    const FUNCTION_CODE_RECRUITMENT = '05036';

    // Performance
    const FUNCTION_CODE_ACTING_BENEFIT_LIST = '05037';
    const FUNCTION_CODE_PROMOTION = '05040';
    const FUNCTION_CODE_INCREMENT_LIST = '05044';
    const FUNCTION_CODE_RESIGN = '05051';
    const FUNCTION_CODE_TRANSFER = '05045';
    const FUNCTION_CODE_TERMINATE_LIST = '05057';
    const FUNCTION_CODE_RETIREMENT_LIST = '05061';

    // Account & loans
    const FUNCTION_CODE_ADVANCED_SALARY_LOAN = '05050';
    const FUNCTION_CODE_ADVANCED_SALARY_LAON_COLLECTION = '05060';
    const FUNCTION_CODE_EDPS = '05038';
    const FUNCTION_CODE_EARLY_SETTLEMENT_OF_VEHICLE_LOAN = '05063';
    const FUNCTION_CODE_SECURITY_MONEY_COLLECTION = '05054';
    const FUNCTION_CODE_SALARY_DEDUCTION = '05096';
    const FUNCTION_CODE_PF_LOAN = '05042';
    const FUNCTION_CODE_INCOME_TAX = '05048';
    const FUNCTION_CODE_VEHICLE_LOAN = '05046';

    // Payroll
    const FUNCTION_CODE_GENERATE_SALARY = '05022';
    const FUNCTION_CODE_FINAL_PAYMENT_SALARY = '05095';
    const FUNCTION_CODE_GRATUITY = '05024';
    const FUNCTION_CODE_GRATUITY_ADJUSTMENT = '05083';
    const FUNCTION_CODE_FESTIVAL_BONUS = '05026';
    const FUNCTION_CODE_PROVIDENT_FUND_INTEREST = '05029';
    const FUNCTION_CODE_SECURITY_DEPOSIT_INTEREST = '05033';
    const FUNCTION_CODE_EDPS_INTEREST = '05034';
    const FUNCTION_CODE_EDPS_RETURN = '05087';
    const FUNCTION_CODE_FINALPAYMENT = '05075';
    const FUNCTION_CODE_FINAL_PAYMENT_COMPLETED = '05082';


    // Report
    const FUNCTION_CODE_LEAVE_STATUS = '05097';
    const FUNCTION_CODE_NEW_APPOINTED_STAFF_MONTHLY = '05090';
    const FUNCTION_CODE_MONTHLY_TOTAL_STAFF_REPORT = '05092';
    const FUNCTION_CODE_CONSOLITED_STAFF_REPORT = '05091';
    const FUNCTION_CODE_HR_NEWLY_APPOINTED_EMPLOYEE_REPORT = '05003';
    const FUNCTION_CODE_HR_PERMANENT_OR_PROMOTION_REPORT = '05004';
    const FUNCTION_CODE_HR_EMPLOYEE_TRANSFER_REPORT = '05005';
    const FUNCTION_CODE_HR_EMPLOYEE_SALARY_REPORT = '05006';
    const FUNCTION_CODE_HR_EMPLOYEE_BONUS_REPORT = '05008';
    const FUNCTION_CODE_HR_EDPS_RECEIVE_REPORT = '05009';
    const FUNCTION_CODE_HR_EMPLOYEE_REPORT = '05001';
    const FUNCTION_CODE_HR_PF_RECEIVE_REPORT = '05010';

    const FUNCTION_CODE_HR_INSURANCE_RECEIVE_REPORT = '05011';
    const FUNCTION_CODE_HR_PF_LOAN_RECEIVE_REPORT = '05014';
    const FUNCTION_CODE_HR_VEHICLE_LOAN_RECEIVE_REPORT = '05016';
    const FUNCTION_CODE_HR_VECHICLE_LOAN_REGISTER_REPORT = '05018';
    const FUNCTION_CODE_HR_SECURITY_MONEY_RECEIVE_REPORT = '05019';
    const FUNCTION_CODE_HR_WF_RECEIVE_REPORT = '05013';
    const FUNCTION_CODE_TOTAL_STAFF_LIST = '05093';
    const FUNCTION_CODE_UPCOMING_PROMOTION_INCREMENT = '05094';
    const FUNCTION_CODE_EARLY_SETTLEMENT_OF_PF_LOAN = '05068';
    const FUNCTION_CODE_PAY_SLIP = '05089';
    const FUNCTION_CODE_EPS_REGISTER = '05088';
    const FUNCTION_CODE_PF_LOAN_REGISTER_REPORT = '05076';
    const FUNCTION_CODE_PF_REGISTER_REPORT = '05077';
    const FUNCTION_CODE_WF_REGISTER_REPORT = '05078';
    const FUNCTION_CODE_SECURITY_DEPOSIT_REGISTER_REPORT = '05079';
    const FUNCTION_CODE_EDPS_REGISTER_REPORT = '05080';
    const FUNCTION_CODE_HR_GRATUITY_FUND_REGISTER_REPORT = '05081';

    // Settings
    const FUNCTION_CODE_OPENINGBALANCE_FUND = '05002';
    const FUNCTION_CODE_OPENING_LEAVE = '05012';
    const FUNCTION_CODE_OPENING_BALANCE_LOAN_PF = '05015';
    const FUNCTION_CODE_DOCUMENT_LIST = '05017';
    const FUNCTION_CODE_HR_GRATUITY_REPORT = '05020';
    const FUNCTION_CODE_OPENING_BALANCE_LOAN_VEHICLE = '05023';
    const FUNCTION_CODE_OPENING_BALANCE_LOAN_ADVANCED_SALARY = '05025';
    const FUNCTION_CODE_REASON = '05028';
    const FUNCTION_CODE_LEAVE_TYPE = '05030';
    const FUNCTION_CODE_EMPLOYEE_REQUISITION_LIST = '05031';
    const FUNCTION_CODE_DOCUMENT = '05032';
    const FUNCTION_CODE_JOB_CIRCULAR_LIST = '05035';
    const FUNCTION_CODE_GRADE = '05039';
    const FUNCTION_CODE_LEVEL = '05041';
    const FUNCTION_CODE_DEPARTMENT = '05043';
    const FUNCTION_CODE_POSITION = '05047';
    const FUNCTION_CODE_SECURITY_MONEY = '05049';
    const FUNCTION_CODE_BENEFIT = '05052';
    const FUNCTION_CODE_BONUS = '05053';
    const FUNCTION_CODE_INTEREST_METHOD = '05055';
    const FUNCTION_CODE_DONATION_SECTOR = '05056';
    const FUNCTION_CODE_EXAM = '05058';
    const FUNCTION_CODE_SETTINGS_OTHER = '05059';
    const FUNCTION_CODE_SALARY_STRUCTURE = '05062';
    const FUNCTION_CODE_SALARY_ADVANCED_RULE = '05064';
    const FUNCTION_CODE_SALARY_AND_BENEFIT = '05065';
    const FUNCTION_CODE_PF_SETTINGS = '05066';
    const FUNCTION_CODE_VECHICLE = '05067';
    const FUNCTION_CODE_VECHICLE_LOAN_SETTINGS = '05069';
    const FUNCTION_CODE_HOLIDAY = '05070';
    const FUNCTION_CODE_INSURANCE_SETTINGS = '05071';
    const FUNCTION_CODE_OSF_SETTINGS = '05072';
    const FUNCTION_CODE_WF_SETTINGS = '05073';
    const FUNCTION_CODE_HR_FUND_AND_LOAN = '05074';
    const FUNCTION_CODE_RESIGN_CANCEL = '05084';
    const FUNCTION_CODE_TERMINATE_CANCEL = '05085';
    const FUNCTION_CODE_HR_EPS_SETTINGS = '05086';
    const FUNCTION_CODE_LEAVE_SETTINGS = '05098';
    const FUNCTION_CODE_LEAVE_SETTINGS_OTHER = '05099';
    const FUNCTION_CODE_HOME = '05100';
}
